In [ ]:
# NumPy Array ek special data structure hai jo numbers ko efficiently store aur process karta hai. Ye Python ki normal list se faster aur memory efficient hota hai.

# number = [1, 2, 3, 4, 5]
# print(number)

[1, 2, 3, 4, 5]


In [ ]:
# Python me import ka matlab hota hai kisi library (module) ko apne program me lana, taaki uske functions aur features use kar sako.
# NumPy library ko Python program ke andar la rahe ho, taaki Python uske functions ko use kar sake.
import numpy as np

In [ ]:
# a = np.array([1, 2, 3, 4, 5])
# print(a)

[1 2 3 4 5]


In [ ]:
# l = [[1, 2, 3], [4, 5, 6]] #multipal arrays ko ek sath store karne ke liye 2D array ka use karte hai.
# print(l)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
# print(np.array(l)) #looking like a 2D array

[[1 2 3]
 [4 5 6]]


In [9]:
# Array generation function :- 
import numpy as np
arr = np.arange(0, 10,1)#0 se 10 tak ke numbers ko 2 ke gap me generate karne ke liye arange function ka use karte hai.,
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr = np.zeros((3,4)) #3 rows and 4 columns ka array generate karne ke liye zeros function ka use karte hai.
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
arr = np.ones((3,4)) #3 rows and 4 columns ka array generate karne ke liye ones function ka use karte hai.
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
arr = np.linspace(1, 10, 5) #0 se 10 tak ke numbers ko 5 equal parts me divide karne ke liye linspace function ka use karte hai.
print(arr)  #esme space dekha jata hai or jitna bada number hoga utna space jyada hoga.5 ke place me 

[ 1.    3.25  5.5   7.75 10.  ]


In [21]:
#random number generation function :- NumPy me Random Generation Functions ka use random numbers generate karne ke liye hota hai
np.random.rand(3)


array([0.42313424, 0.53819714, 0.93258645])

In [36]:
np.random.randint(2474)#10 ke beech me 5 random numbers generate karne ke liye randint function ka use karte hai.

256

In [40]:
np.random.randn(3) #3 random numbers generate karne ke liye randn function ka use karte hai.

array([ 1.56617224, -0.64920076,  0.21414134])

In [49]:
# Array Attribute :-Array Attributes ka matlab hai array ki properties jaise shape, size, dimensions, data type, etc.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr) #shape ka matlab hai array ke dimensions, jaise rows aur columns ki sankhya.


[[1 2 3]
 [4 5 6]]


In [50]:

print(arr.shape) #shape ka matlab hai array ke dimensions, jaise rows aur columns ki sankhya.

(2, 3)


In [47]:
print(arr.size)#esse size batata hai 

6


In [48]:
print(arr.dtype) #esse data type batata hai

int64


In [ ]:
#Array method :- NumPy Array Methods wo functions hote hain jo array par operations perform karte hain.

print(arr.max)

<built-in method max of numpy.ndarray object at 0x00000217B754D470>


In [ ]:
arr.sum() 

np.int64(21)

In [58]:
np.sum(arr,axis = 0) #axis = 0 ka matlab hai ki hum rows ke across sum kar rahe hain, yani har column ka sum nikal rahe hain.

array([5, 7, 9])

In [59]:
arr.mean() #mean ka matlab hai average, yani array ke elements ka average nikalna.

np.float64(3.5)

In [ ]:
# argmax ka matlab hai array me sabse bada element ka index nikalna.
arr = np.array([[1, 2, 3], [4, 5, 6]])  # define a fallback array (or run the cell that sets `arr`)
print(arr.argmax())

NameError: name 'arr' is not defined