In [2]:
import numpy as np

In [1]:
#numpy indexing and slicing of vectors

In [ ]:
import numpy as np
arr = np.arange(11,21) #create in indexed
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [4]:
print(arr[:4])

[11 12 13 14]


In [6]:
print(arr[::3]) #array slicing with step size of 3 matlab ki array se 3 step se jump karega 

[11 14 17 20]


In [8]:
# Reverse Alternate Elements
print(arr[::-2]) #esme humne array ko reverse kiya aur alternate elements print karaye

[20 18 16 14 12]


In [ ]:
# Slice with Start, Stop, Step
import numpy as np
print(arr[1:7:2])
print(arr[::2]) #esme humne array ko reverse kiya aur alternate elements print karaye


NameError: name 'arr' is not defined

In [1]:
# NUMPY INDEXING AND SLICING OF MATRIX
# A matrix is a 2D NumPy array consisting of rows and columns.
arr = np.arange(1,17).reshape(4,4) #create a 4x4 matrix  .... reshape me 1 value column ki de jati hai or second value row ki de jati hai
arr

NameError: name 'np' is not defined