In [2]:
import numpy as np

In [1]:
#numpy indexing and slicing of vectors

In [ ]:
import numpy as np
arr = np.arange(11,21) #create in indexed
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [4]:
print(arr[:4])

[11 12 13 14]


In [6]:
print(arr[::3]) #array slicing with step size of 3 matlab ki array se 3 step se jump karega 

[11 14 17 20]


In [8]:
# Reverse Alternate Elements
print(arr[::-2]) #esme humne array ko reverse kiya aur alternate elements print karaye

[20 18 16 14 12]


In [6]:
# Slice with Start, Stop, Step
import numpy as np
print(arr[1:7:2])


[[ 5  6  7  8]
 [13 14 15 16]]


In [5]:
# NUMPY INDEXING AND SLICING OF MATRIX
# A matrix is a 2D NumPy array consisting of rows and columns.
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
slice = arr[3:,3:] #slicing of matrix
slice 

array([[16]])

In [9]:
arr[:,2]

array([ 3,  7, 11, 15])

In [10]:
# BOOLEAN INDEXING  : - Boolean Indexing ka use kisi condition ke basis par array se values ko select ya filter karne ke liye hota hai.

In [11]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index = arr % 2 == 0 #ye condition hai ki array ke elements ko 2 se divide karne par remainder 0 aaye to wo even number hai
bool_index

array([ True,  True,  True,  True,  True])

In [ ]:

arr = arr[bool_index] #ye condition ke basis par array ke even numbers ko select kar raha hai
arr

array([12, 14, 16, 18, 20])