In [2]:
# valid sudoku 
import numpy as np

In [ ]:
s = np.array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
              [6, 7, 2, 1, 9, 5, 3, 4, 8],
              [1, 9, 8, 3, 4, 2, 5, 6, 7],
              [8, 5, 9, 7, 6, 1,4, 2, 3],
              [4, 2, 6, 8, 5, 3, 7, 9, 1],
              [7, 1, 3, 9, 2, 4, 8, 5, 6],
              [9, 6, 1, 5, 3, 7, 2, 8, 4],
              [2, 8, 7, 4, 1, 9, 6, 3, 5],
              [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [10]:
b = np.sum(s, axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [12]:
c = np.sum(s, axis = 1)
for i in c:
    if i != 45:
        print("Not a valid sudoku")
        break
else:
    print("Valid sudoku")


Valid sudoku


In [ ]:
for j in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n.sum())
        


[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]
[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]
[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [38]:
import numpy as np
#columns : [Age ,Maths Marks, Science Marks,]
data = np.array([[18,85,78],
                [19,92,88],
                [17 ,76,78],
                [18,89,90],
                [19,95,92],
                [17,80,85],
                [18,88,87],
                [19,91,89],
                [17,75,80],
                [18,86,84]])

In [39]:
#Get the Shape of the matrix
data.shape


(10, 3)

In [40]:
#Find the average of each student
np.mean(data[:,0])

np.float64(18.0)

In [41]:
# Extrect Maths marks of all students
data[:,1]

array([85, 92, 76, 89, 95, 80, 88, 91, 75, 86])

In [42]:
#Find the highest marks in Science
np.max(data[:,2])

np.int64(92)

In [43]:
#Get details of student who scored more than 90 in maths

data[data[:,1] > 90]

array([[19, 92, 88],
       [19, 95, 92],
       [19, 91, 89]])

In [44]:
#increase the maths marks of all students by 5
data[:,1] + 5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 78],
       [18, 89, 90],
       [19, 95, 92],
       [17, 80, 85],
       [18, 88, 87],
       [19, 91, 89],
       [17, 75, 80],
       [18, 86, 84]])

In [45]:
# Find how many student are younger than 19

len(data[data[:,0] < 19])


7

In [47]:
#calculate the average marks in each subject (column-wise mean ).
np.mean(data[:,1:],axis = 0)

array([85.7, 85.1])

In [49]:
# Get data of student who scored at least 80 in both subject 

data[(data[:,1] >= 80) & (data[:,2] >=80)]

array([[19, 92, 88],
       [18, 89, 90],
       [19, 95, 92],
       [17, 80, 85],
       [18, 88, 87],
       [19, 91, 89],
       [18, 86, 84]])

In [53]:
# Replace all science marks < 75 with 0

data[:,2] [data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 78],
       [18, 89, 90],
       [19, 95, 92],
       [17, 80, 85],
       [18, 88, 87],
       [19, 91, 89],
       [17, 75, 80],
       [18, 86, 84]])