In [1]:
# ARRAY OPERATIONS

In [5]:
# Artihematic operations on arrays are usually done on an element-by-element basis. This is called vectorization. Vectorization is a way of computing results without writing any for loops. It is a very powerful tool in NumPy, and it can lead to more concise and readable code.
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])



In [7]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1-a2

array([-5, -5, -5, -5, -5])

In [9]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [12]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [14]:
# BROADCASTING : - Broadcasting ek feature hai jo NumPy ko different shapes ke arrays par arithmetic operations (addition, subtraction, multiplication, division, etc.) perform karne deta hai without manually copying data.

In [3]:
import numpy as np
l = [10,20,30,40,50,60,70,80,90,100]
print(l)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [4]:
arr+10

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [5]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [7]:
# DEEP AND SHALLOW COPY : - Deep copy and shallow copy are two different ways of copying data in programming. A deep copy creates a new object with a new memory address, while a shallow copy creates a new reference to the same object in memory.

In [13]:
a = np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [18]:
a[4:10]
#esme 5 se le kr 10 tk print ho jayega 

array([ 5,  6,  7,  8,  9, 10])

In [19]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a
b = a

In [23]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
# MATRIX OPERATIONS :- 

In [33]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])


In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [36]:
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [39]:
np.dot(6,7)

np.int64(42)

In [40]:
# ADVANCE ARRAYS MANIPULATION :- 

In [41]:
# Stack :- Stacking is a technique used in NumPy to combine multiple arrays into a single array along a specified axis. It allows you to create higher-dimensional arrays by stacking lower-dimensional arrays together.

In [43]:
a = np.array([[1,2,3,4,5,6,]])
b = np.array([[7,8,9,10,11,12]])

In [44]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [47]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [48]:
np.column_stack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [49]:
# spliting arrays :- Splitting arrays in NumPy refers to the process of dividing an array into multiple smaller arrays along a specified axis. This can be useful for various purposes, such as data preprocessing, parallel processing, or simply organizing data into manageable chunks.

In [50]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]